# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Vue App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosts
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: rsync -arv --delete dist/ /Users/hangeat/Public/frontend
